import Spark from "../../components/Spark";
import "./About.css";

export default function AboutPage({ children }) {
  return (
    <div className="about-page">
      <Spark />
      <div className="about-content body--copy">
        <p>Fabric was founded in 2022, with seed funding from Polychain Capital, Eniac Ventures, Mischief, and Reverie. The Fabric team is Jonny Mack, Dan Simpson, and Chris Douglas.</p>
        <p>Our first product was an <a href="">onchain</a> <a href="">crowdfunding</a> <a href="">protocol</a> and <a href="">user</a> <a href="">interface</a>, launched in April of 2023. ~$500k was raised by 377 campaigns from 916 unique contributors. Some of our favorites were <a href="https://crowdfi.withfabric.xyz/campaign/farcaster-meetup-fund-12vw1bash08hs">Farcaster Meetup Fund</a>, <a href="https://crowdfi.withfabric.xyz/campaign/farcon-fund-1-pj66h3w2gc8w">FarCon Fund</a>, <a href="https://crowdfi.withfabric.xyz/campaign/fabric-on-base-1fctinte15urk">FABRIC on BASE</a>, <a href="https://crowdfi.withfabric.xyz/campaign/model-wip-13m5e2kzo8su8">MODEL-WIP</a>, and <a href="https://crowdfi.withfabric.xyz/campaign/farcon-2024-pre-commit-4x2ya8uejw8w">FarCon 2024</a>.</p>
        <p>Our second product was an onchain <a href="">subscription</a> <a href="">protocol</a> and <a href="">user interface</a>, launched 6 months later in October of 2023. $1.2m was earned by 2,279 unique creators from 45,287 unique subscribers. Some of our favorites were <a href="https://hypersub.xyz/s/eic-quarterly-7ap108nf7bb4">EIC Quarterly</a>, <a href="https://hypersub.xyz/s/the-yon-experience-w4nphk0hhc00/drops">the yon experience</a>, <a href="https://hypersub.xyz/s/aether-8pvtiwcxwqo0">Aether</a>, <a href="https://hypersub.xyz/s/mbranson/drops">m/branson</a>, <a href="https://hypersub.xyz/s/the-geometric-circle/drops">The Geometric Circle</a>, <a href="https://hypersub.xyz/s/atelie-407-o61meh6sieww/drops">Ateliê 407</a>, and <a href="https://hypersub.xyz/s/patronsofblue/drops">Patrons of Blue</a>.</p>
        <p>Our third product, launching in 2026, is a swap routing API, benchmarking tool, and user interface.</p>
        <p>With each iteration of the company we've learned, grown, and adapted to market reality. Though our products have taken many forms, our motivations remain the same: permissionless capital coordination, efficient markets, economic freedom.</p>
        <img src="/images/team.jpg" alt="" />
        <p><span>Jonny Mack</span> is the cofounder and CEO of Fabric. Previously, he was the principal of Nonlinear, a design consultancy focused on user research, product design, and prototyping for early stage startups. His clients included Coinbase, Unit 410, Polychain, Roll, Awair, and Observable. Before that he was a design lead on Chrome OS and Android system UI, cofounder of Google Domains, and lead designer for Google‘s Cloud Console. Jonny also worked as a prototyper on webOS at HP, a freelance designer, and an artist assistant to Shepard Fairey and Dave Kinsey.</p>
        <p><span>Dan Simpson</span> is the cofounder and CTO of Fabric. Previously, he was CTO at One More Cloud, where he built the search infrastructure for companies such as Pinterest, GitHub, HBO, Heroku, and OfferUp. Before that, he cofounded KLATU Networks, which developed predictive monitoring systems for life science applications. Dan was also the founding engineer for CryoPort, a logistics platform for cryogenic materials, and TRAXX, a system for wireless hardware analytics.</p>
        <p><span>Chris Douglas</span> is the cofounder and CSO of Fabric, and a professor of mathematics at the University of Oxford. He cofounded and co-directed the Centre for Quantum Mathematics and Computation, and was a founding editorial board member of Ledger, the first academic journal dedicated to cryptocurrency and blockchain technology research. Before joining the Oxford faculty, Chris was a Rhodes Scholar, a graduate student at MIT, a postdoc at Stanford, and a research fellow at the Miller Institute at the University of California, Berkeley.</p>
      </div>
    </div>
  )
}